---
- name: Test playbook
  hosts: all

  tasks:
  - name: Cat current config
    command: cat /tmp/web.config
    register: command_output

  - name: Print
    debug:
      msg: "{{command_output.stdout}}"
