---
- name: Test playbook
  hosts: all

  vars:
    config_path: /tmp/web.config
    configs:
    - { regex: 'XXX', line: 'YYY' }
    - { regex: 'WWW', line: 'ZZZ' }
    

  tasks:
  - name: Cat current config
    lineinfile:
      path: "{{ config_path }}"
      regex: "{{ item.regex }}"
      line: "{{ item.line }}"
    loop: "{{ configs }}"
