---
- name: Test playbook
  hosts: all

  vars:
    config_path: /tmp/web.config
    envParams:
    - LoginUrl="This is a test"
    - proxy=YES
    configs: "{{ envParams | map('split', '=') | list }}"
    #- { regex: 'XXX', line: 'YYY' }
    #- { regex: 'WWW', line: 'ZZZ' }
    

  tasks:
  - name: Display config
    debug:
      msg: "{{ item }}"
    with_items:
      - "{{ configs }}"
    
  #- name: Cat current config
  #  lineinfile:
  #    backrefs: true
  #    path: "{{ config_path }}"
  #    regex: "{{ item.regex }}"
  #    line: "{{ item.line }}"
  #  loop: "{{ configs }}"
