---
- name: Test playbook
  hosts: all

  vars:
    config_path: /tmp/web.config
    envParams:
    - key: LoginUrl
      value: "This is a test"
    - key: proxy 
      value: YES
    configs: "{{ envParams | map('split', '=') | list }}"
    #- { regex: 'XXX', line: 'YYY' }
    #- { regex: 'WWW', line: 'ZZZ' }
    
  tasks:
  - name: Cat current config
    lineinfile:
      backrefs: true
      path: "{{ config_path }}"
      regex: "{{ item.key }}"
      line: "<add key=\"{{ item.key }}\" value=\"{{ item.value }}\" />"
    loop: "{{ envParams }}"
