---
- name: Test playbook
  hosts: all

  vars:
    config_path: /tmp/web.config

  tasks:
  - name: Cat current config
    lineinfile:
      path: "{{ config_path }}"
      line: This is a new line
      state: present
      create: true
